### ISSUE TITLE
Asal sayı

### ISSUE THREAD

**Issue by Mavrikant** [mstfsbrkrmn/Python#1]
https://github.com/mstfsbrkrmn/Python/blob/03e7c3aec9d2a5392a204bea22e65f0d28e7c80a/Egzersizler/5_Asal_say%C4%B1_m%C4%B1_.ipynb

Yukarıdai kodu inceledim. Bütün sayıları kontrol etmene gerek yok. 
**s** sayısının kareköküne kadar olan sayıları kontrol etmen yeterli. Çünkü daha büyük bir sayını tam katı olamaz.

**Comment by mstfsbrkrmn** [comment]
anladım, çözdüm.
dosyayı githubtan güncelleyemedim, güncel halini tekrar yükledim.
https://github.com/mstfsbrkrmn/Python/blob/master/Egzersizler/5_Asal_say%C4%B1_m%C4%B1.ipynb

**Comment by Mavrikant** [comment]
i++ şeklinde ilerlemene yine gerek yok. i=i+2 şeklinde ilerleyebilirsin. Eğer çift sayıya bölünebiliyorsa asal olamaz zaten ve 2ye bölünüp bölünmediği ilk başta kontrol ediyorsun.
